### ISSUE TITLE
Horusec Github Actions

### ISSUE THREAD

**Issue by fguisso** [ZupIT/horusec#103]
Some tools for GitHub actions show errors separate by line and can point to the specific line in the code, I do'nt know who it's wokin the github actions, but if anyone give me direction, I can work in this issue.

Today running `horusec -e="true"` give just one error in the action and it's not so good for read.

**Comment by wiliansilvazup** [comment]
Thanks for the reported report! @fguisso
Currently the function of the `-e =" true "` flag is just to know if among the problems found there is one of the type *Vulnerability* in your code, so return exit(1) in the pipeline.
You have a few exits:
* correct the errors reported by Horusec so that there is no more vulnerability in your code;
* check if it is a false positive or accepted risk;
* among other ways to validate whether I want my pipeline to break or not due to the problem encountered.

If you want to integrate with any Github Actions tool, when you click on the vulnerability you are redirected to the code, it would be incredible. =)
For that I would use some kind of redirect link through the directory of the file that horusec found.
Just be careful as we don't only work with Github Actions in order to be something very exclusive and maybe break into other pipelines =)

Good Luck!
