### ISSUE TITLE
Allow passing false positives as an array in the horusec-config.json file

### ISSUE THREAD

**Issue by antoniofilhozup** [ZupIT/horusec#157]
**Summary**
Currently, the `horusec-config.json` file allows the `ReferenceHashes` of the false positives to be passed through `horusecCliFalsePositiveHashes` key. But the documentation specifies that they are separated by a comma in a single string, making this string very long if they have many false positives.
It would be interesting if it were possible to pass an array of strings instead of a single string.

**What would you like to be added**:
Allow passing false positives as an array in the `horusec-config.json` file

**Why is this needed**:
To facilitate readability and maintenance of the `horusec-config.json` file

**Comment by wiliansilvazup** [comment]
hello @antoniofilhozup 
Thanks for the feedback!
The horusec team has already put in its script to perform due to the change, but as it will generate some _breaking changes_ we chose to leave it to make it later.
All Horusec configurations are performed as follows, overwriting each other respectively:
* we acquired the data using [Viper](https://github.com/spf13/viper) by reading the configuration file `horusec-config.json`;
* we acquire the values of the environment variable;
* we acquired the data passed by the flag using [Cobra](https://github.com/spf13/cobra);
As there are several validations to be carried out so that all configurations work in harmony, it is a change that requires some time, but we will check as soon as we can add it to the project.

If you are interested in making this change we will be very happy to show you the way to do it :)
