### ISSUE TITLE
Add Spotbugs for Java/Kotlin

### ISSUE THREAD

**Issue by javixeneize** [ZupIT/horusec#162]
**What would you like to be added**: Spotbugs is probably the most reliable opensource tool to scan Java code, this might be added here 

**Why is this needed**: To improve Java quality scan

**Comment by wiliansilvazup** [comment]
Hello @javixeneize 

Thanks for pointing out this improvement!
We currently have an integration with the spotbugs [in this directory](https://github.com/ZupIT/horusec/tree/master/horusec-cli/internal/services/formatters/java/spotbugs), but due to the fact that when performing the test, several projects had difficulties in their analysis, some of them were:
* Downloading private libraries was not being possible without authentication.
* Analysis generating several false positives.
* (Main) Extremely slow delivery of results.
In view of these points we chose to depreciate the use of spotbugs within Horusec and create the [Horusec-Java](https://github.com/ZupIT/horusec/tree/master/horusec-java) and [Horusec-Kotlin](https://github.com/ZupIT/horusec/tree/master/horusec-kotlin) tool where most of the rules that can be applied via syntax analysis are covered by these tools!
If you are interested in adding this tool to your personal project just create a fork of horusec and we can direct you to enable the tool again, but we currently have no forecast for releasing the tool within the platform.
