### ISSUE TITLE
Semantic Analysis

### ISSUE THREAD

**Issue by shpandrade** [ZupIT/horusec#176]
**What happened**:

We're evaluating Horusec, conducting tests in order to understand how we can implement the solution in our project.
According to what had already been treated through: https://github.com/ZupIT/horusec/issues/159
We were reported that the solution works with syntactic analysis, but doesn't include semantic analysis.
Important is the possibility of semantic analysis so that it is possible to identify and "correlate" variables.

Example:

![image](https://user-images.githubusercontent.com/74913648/101076556-500d4680-3582-11eb-9a3b-9c2021229207.png)

Is there a roadmap or target date for the semantic analysis to be covered?

**Environment:**

Horusec version: 1.5.0
Operating System: Ubuntu 18.04

**Comment by wiliansilvazup** [comment]
Hi @shpandrade 
We still don't have a forecast to start doing semantic analysis! What happens is that this type of analysis is very complex and involves a lot of study and research, today for example we support several languages ​​and to have the same support of semantic analysis we need to be able to generate the AST of each language in order to simulate the code flow and create rules to find vulnerabilities within that flow, in addition to this complexity the rules to be created are also more complex as parsing is already an excellent way to report possible vulnerabilities, although it does generate a greater number of false positives and not being able to get some things we need to know the flow of code and context we decided to focus the studies on another approach to vulnerability analysis
basically a strategic decision today we are doing research on symbolic analysis to also have a dast in the application but still not foreseen is in the study phase.
