### ISSUE TITLE
horusec-messages and horusec-webhook keep throwing a runtime error

### ISSUE THREAD

**Issue by kamal-ma** [ZupIT/horusec#430]
**What happened**: horusec-messages and horusec-webhook keep throwing a runtime error in the terminal and the web app itself is working but signup not working with this message from the browser "SOMETHING UNEXPECTED HAPPENED, TRY AGAIN."
And this is the log from the terminal
`horusec-messages    | panic: runtime error: invalid memory address or nil pointer dereference
horusec-messages    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x89b8dd]
horusec-messages    | 
horusec-messages    | goroutine 1 [running]:
horusec-messages    | github.com/streadway/amqp.(*Connection).IsClosed(...)
horusec-messages    | 	/go/pkg/mod/github.com/streadway/amqp@v1.0.0/connection.go:355
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/services/broker.(*Broker).setUpConnection(0xc000676120, 0xc000676120, 0x0)
horusec-messages    | 	/horusec/development-kit/pkg/services/broker/broker.go:56 +0x9d
horusec-messages    | github.com/ZupIT/horusec/development-kit/pkg/services/broker.NewBroker(0xc03548, 0xc000ba0000, 0xbfbb80, 0xc000678948, 0x0, 0x0)
horusec-messages    | 	/horusec/development-kit/pkg/services/broker/broker.go:44 +0x8d
horusec-messages    | github.com/ZupIT/horusec/horusec-messages/config/broker.SetUp(0xbfbb80, 0xc000678948, 0x10c3328f735d94, 0xc00003e710)
horusec-messages    | 	/horusec/horusec-messages/config/broker/broker.go:28 +0x2b
horusec-messages    | main.main()
horusec-messages    | 	/horusec/horusec-messages/cmd/app/main.go:39 +0x4c
horusec-messages    | panic: runtime error: invalid memory address or nil pointer dereference
horusec-messages    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x89b8dd]
`
`horusec-webhook     | panic: runtime error: invalid memory address or nil pointer dereference
horusec-webhook     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0xac09dd]
horusec-webhook     | 
horusec-webhook     | goroutine 1 [running]:
horusec-webhook     | github.com/streadway/amqp.(*Connection).IsClosed(...)
horusec-webhook     | 	/go/pkg/mod/github.com/streadway/amqp@v1.0.0/connection.go:355
horusec-webhook     | github.com/ZupIT/horusec/development-kit/pkg/services/broker.(*Broker).setUpConnection(0xc0001adfe0, 0xc0001adfe0, 0x0)
horusec-webhook     | 	/horusec/development-kit/pkg/services/broker/broker.go:56 +0x9d
horusec-webhook     | github.com/ZupIT/horusec/development-kit/pkg/services/broker.NewBroker(0xfc7328, 0xc00009cf80, 0x9b14d8, 0xc00003c01d, 0x8, 0xc00003a019)
horusec-webhook     | 	/horusec/development-kit/pkg/services/broker/broker.go:44 +0x8d
horusec-webhook     | github.com/ZupIT/horusec/horusec-webhook/config/broker.SetUp(0xfc5ed0, 0xc00010c008, 0x10c3329d677326, 0xc000052710)
horusec-webhook     | 	/horusec/horusec-webhook/config/broker/broker.go:28 +0x2b
horusec-webhook     | main.main()
horusec-webhook     | 	/horusec/horusec-webhook/cmd/app/main.go:39 +0x4c
horusec-webhook     | panic: runtime error: invalid memory address or nil pointer dereference
horusec-webhook     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0xac09dd]
`

**What you expected to happen**: Expect the tool to work. 

**How to reproduce it (as minimally and precisely as possible)**: Same steps here "https://horusec.io/docs/web/installation/install-with-docker-compose/". Cloned the repo, run make install

**Environment**: 
- Horusec version (use `horusec version`): https://horusec.io/docs/web/installation/install-with-docker-compose/
- Operating System: Amazon Linux 2 "5.4.95-42.163.amzn2.x86_64" and RedHat "3.10.0-1160.21.1.el7.x86_64"
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by wiliansilvazup** [comment]
tnks for your report @kamal-ma 

If you have not made any changes to the docker-compose. Provide us with some more information such as:
* Docker version used
* Version used in the services and if you are using the latest image version I suggest performing [a cleaning of the local images] (https://docs.docker.com/engine/reference/commandline/system_prune/) and try again!

If you have modified the docker-compose to NOT use the messaging service as shown [in our tutorial] (https://horusec.io/docs/tutorials/how-to-enable-disable-messaging-service/), then this is normal behavior because the services will not be exposed and no connection to the message-broker will be initiated!

**Comment by wiliansilvazup** [comment]
In tests on my local machine there are actually some error logs because the RabbitMQ message broker is not available and it will restart the service until it has a stable connection between them. So you can see that in the end the service was exposed and is running successfully!
![image](https://user-images.githubusercontent.com/63816070/114912961-ff8edb00-9df6-11eb-9d48-6f6cd6e4a5b9.png)

**Comment by kamal-ma** [comment]
@wiliansilvazup 

- My docker-compose version is ` 1.29.1, build c34c88b2` and I tried an older version which was `1.24.1, build 4667896b` still the same behavior.
- The amazon linux machine was a completely new machine, no local images of any kind.
- I haven't modified anything in any files or removed the messaging service except for adding the SMTP credentials to fix the "password cannot be blank" error.
- The last line of the make install had the horusec version `Actual version installed of the horusec is: v1.10.1`. Other services have the same versions as the compose file on the repo, no versions had been modified.

**Comment by wiliansilvazup** [comment]
By default is not necessary pass smtp credentials, because broker is [not enable in docker-compose](https://github.com/ZupIT/horusec/blob/master/deployments/docker-compose.yaml#L127), if you see the environment variable `HORUSEC_DISABLED_BROKER` your value is `true`. This configuration default, to the services *horusec-messages* and *horusec-webhook* will not be used within the web application.

To enable and usage this services you can see more [in our tutorial](https://horusec.io/docs/tutorials/how-to-enable-disable-messaging-service/)

**Comment by wiliansilvazup** [comment]
i will close issue for now, if you need help is possible reopen this issue
