### ISSUE TITLE
DOCKER_HOST not taken into account

### ISSUE THREAD

**Issue by socotra69** [ZupIT/horusec#525]
**What happened**:
- In a context where the docker host is different from the default configuration, the docker services cannot works.
In other word, the DOCKER_HOST env var is not used by the program.
- in my case in did not work in a docker dind context setted up on a bitbucket pipeline

**What you expected to happen**:
DOCKER_HOST env var should be the law.

**How to reproduce it (as minimally and precisely as possible)**:
Create a docker service and expose it from another host.
Set the DOCKER_HOST var on the machine.
Validate conf with a simple docker run busybox.
Start horusec

**Anything else we need to know?**:
It is related to the docker client creation.
https://github.com/ZupIT/horusec/blob/02a5f259f415140caa2aa798d3b9cf1c76a19ecd/internal/services/docker/client/docker_config.go#L25
it should be : 
`dockerClient, err := docker.NewClientWithOpts(docker.FromEnv)`

**Environment**:
- Horusec version (use `horusec version`): latest
- Operating System: linux / docker dind
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by wiliansilvazup** [comment]
Hello @socotra69 

Sorry for the delay in returning and we really appreciate the feedback.
This is a very interesting idea, the engineering team will check as soon as possible to inform you about this change and its impacts on Horusec-CLI

If the impact on the tool is low, it is a very valid exchange, otherwise we will have to assess how we can make the appropriate change without impacting user interaction.
