### ISSUE TITLE
engine: flag --information-severity is not working.

### ISSUE THREAD

**Issue by lucasbrunozup** [ZupIT/horusec#785]
**What happened**:
When performing an analysis with the `--information-severity` flag, vulnerabilities of type `INFO` are not being listed.

**What you expected to happen**:
Accuse vulnerabilities of type `INFO` by informing the corresponding flag.

**How to reproduce it (as minimally and precisely as possible)**:
The `examples/javascript/example1` folder contains the following code snippet:
```
  app.listen(PORT, () => {
     console.log(`horus intentionally vulnerable test API is running on port: ${PORT}`)
   });
```
In this snippet, the `HS-JAVASCRIPT-1` vulnerability of the `INFO` type should be accused.

When running an analysis on that folder, using the `--information-severity` flag, this vulnerability is not accused.

**Anything else we need to know?**:
I checked the rule regex, and it is valid for this snippet.

**Environment**:
- Horusec version: v2.6.4
- Operating System: Ubuntu 20.04

**Comment by matheusalcantarazup** [comment]
I think that the problem here is that the flag `--information-severity` has a conflict with `--ignore-severity`.  The default values of --ignore-severity is "INFO", so when we call using the --information-severity the validation [here](https://github.com/ZupIT/horusec/blob/main/internal/controllers/analyzer/analyzer.go#L209) does not remove de `INFO` severities, but since the `INFO` is the default severity type that should be removed the [` removeVulnerabilitiesBySeverity`](https://github.com/ZupIT/horusec/blob/f1f239c4da39effb1569963a1274623b9567c431/internal/controllers/analyzer/analyzer.go#L634) remove these vulnerabilities. 

If we execute `horusec start -p examples/javascript/example1/ --information-severity --ignore-severity ""` we get the correct result, but I don't know if this should be the correct behavior. I think that when we set the `--information-severity` the "INFO" severity should be removed from `--ignore-severity` default values.

cc @nathanmartinszup @wiliansilvazup @iancardosozup

**Comment by nathanmartinszup** [comment]
> I think that the problem here is that the flag `--information-severity` has a conflict with `--ignore-severity`. The default values of --ignore-severity is "INFO", so when we call using the --information-severity the validation [here](https://github.com/ZupIT/horusec/blob/main/internal/controllers/analyzer/analyzer.go#L209) does not remove de `INFO` severities, but since the `INFO` is the default severity type that should be removed the [` removeVulnerabilitiesBySeverity`](https://github.com/ZupIT/horusec/blob/f1f239c4da39effb1569963a1274623b9567c431/internal/controllers/analyzer/analyzer.go#L634) remove these vulnerabilities.
> 
> If we execute `horusec start -p examples/javascript/example1/ --information-severity --ignore-severity ""` we get the correct result, but I don't know if this should be the correct behavior. I think that when we set the `--information-severity` the "INFO" severity should be removed from `--ignore-severity` default values.
> 
> cc @nathanmartinszup @wiliansilvazup @iancardosozup

I believe that is correct, any severity pointed out in `--ignore-severity` will be excluded from the result.

**Comment by matheusalcantarazup** [comment]
> I believe that is correct, any severity pointed out in `--ignore-severity` will be excluded from the result.

Even if we use `--information-severity`? This make no sense to me.

**Comment by iancardosozup** [comment]
I agree with @matheusalcantarazup , we should change the default value from `--ignore-severity` when `--information-severity` is setted via flag/config/environment. If it caused trouble for maintainers to understand i can't imagine for a user

**Comment by nathanmartinszup** [comment]
> > I believe that is correct, any severity pointed out in `--ignore-severity` will be excluded from the result.
> 
> Even if we use `--information-severity`? This make no sense to me.

Ooh I get it, I was misinterpreting. I agree with the change on the default value. But it might also be a good idea to add a warning if the user is passing both settings.
