### ISSUE TITLE
RuleIDs are not present in all engines

### ISSUE THREAD

**Issue by anthturner** [ZupIT/horusec#949]
**What would you like to be added**:
Rule IDs to quickly differentiate flagged items on engines other than HorusecEngine.

**Why is this needed**:
If we are adding RuleId elsewhere (as in SARIF or JSON), having content to populate that field will be necessary.

I created an example of what I'm thinking here:
https://github.com/anthturner/horusec/commit/71f2b4939ceccca0fe4b59949785cb5c5d892d77

I'll be happy to continue building it out if the community thinks this is the right approach.

**Comment by matheusalcantarazup** [comment]
I like the idea about adding a rule id to vulnerabilities of other tools, but I don't think that the ideia described in this commit would be a good approach. I think that the id should be consistency between all vulnerabilities and tools. For example, I don't think that [using the filename](https://github.com/anthturner/horusec/commit/71f2b4939ceccca0fe4b59949785cb5c5d892d77#diff-41524cd60ebf3198509e9768b3670e8d0ad472e03a0954081620adb39db37bffR105) as a rule id suffix would be good, since this filename could be any value.

I also think that the solution that we found here should be compatible with all tools that we support, for example, I don't like the idea of using the [vulnerable code](https://github.com/anthturner/horusec/commit/71f2b4939ceccca0fe4b59949785cb5c5d892d77#diff-41524cd60ebf3198509e9768b3670e8d0ad472e03a0954081620adb39db37bffR105) for a tool and  the [vulnerability title](https://github.com/anthturner/horusec/commit/71f2b4939ceccca0fe4b59949785cb5c5d892d77#diff-41524cd60ebf3198509e9768b3670e8d0ad472e03a0954081620adb39db37bffR105) for other tool, the id implementation should be consistency. [CheckID](https://github.com/anthturner/horusec/commit/71f2b4939ceccca0fe4b59949785cb5c5d892d77#diff-41524cd60ebf3198509e9768b3670e8d0ad472e03a0954081620adb39db37bffR105) from semgrep wold be a good approach, but not all tools have an id like that.

What do you guys think about it? @wiliansilvazup @iancardosozup @nathanmartinszup 


Thank very much to bring this discussion @anthturner

**Comment by anthturner** [comment]
Wanted to move this over here...


> > Correct. RuleID is a string rather than object. It's mostly just used for correlation between multiple files/lines which have the same violation type.
> 
> [According to the documentation](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#result-object) this field is optional, can we follow with this implementation separately from adding the rule id for all vulnerabilities?
> 
> Maybe for this initial implementation we can leave this rule id empty (for vulnerability that was not found by horusec engine) and when we found a solution for #949 we will automatically have this value on output for all tools.
> 
> I'm not finding the `helpUri` and `informationUri` fields on [docs](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#result-object), these fields is optional too? If it yes we can use the same approach described above.
> 
> cc @wiliansilvazup @nathanmartinszup @iancardosozup

I'm fine dropping the URIs -- again, those were originally for my own purposes, since they can link out to corresponding doc pages. That's incredibly useful for developers to help them fix an error they may not understand.

A lot of how I'm thinking of this visually can be seen by using:
https://microsoft.github.io/sarif-web-component/

I've attached two sample SARIF files (as TXT, because of GitHub limitations)

[sample-a.sarif.txt](https://github.com/ZupIT/horusec/files/7926660/sample-a.sarif.txt) -- This one uses `RuleId` for grouping
[sample-b.sarif.txt](https://github.com/ZupIT/horusec/files/7926661/sample-b.sarif.txt) -- This one does not group

These files can be used with the above viewer to visualize what this might look like in an external tool.

You can probably see how scaling this out to what could be hundreds, if not thousands, of vulnerabilities across large targets (as in my use case) would be challenging without an adequate grouping mechanism. Just a thought. 😄

_Originally posted by @anthturner in https://github.com/ZupIT/horusec/issues/946#issuecomment-1020226101_

**Comment by nathanmartinszup** [comment]
Currently each `RuleID` identifies a single vulnerability and this id will never change from project to project, I believe that the idea would be to keep this behavior for all the tools, but nothing comes to mind that would work for everyone. Using such volatile data as filename and code would remove the initial idea of ​​a unique identifier for the vulnerability, regardless of context.

**Comment by iancardosozup** [comment]
I think it wouldn't be a problem to use tools specific ids when we have it (as in [scs tool](https://github.com/ZupIT/horusec/blob/main/internal/services/formatters/csharp/scs/entities.go#L35)). The problem is having a standard way to do it when we don't have an id.
We can create our own way to make an id as in @anthturner idea but i see some problems we must deal with:

- ensure we will have an unique id
- ensure when tool have some update, id must remain the same

but i have some questions too:

- id size must be limited in some way?
- if we choose to creating a hash the same way we do for [vulnerabilities](https://github.com/ZupIT/horusec/blob/main/internal/utils/vuln_hash/vuln_hash.go#L31), how we would guarantee it won't have any change?
- it's okay to have an standard way for our engine and another to orchestrated tools?

**Comment by iancardosozup** [comment]
> RuleId SARIF spec might help with some of these questions: http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html#_Toc517436064

_"Not all existing analysis tools emit the equivalent of a ruleId in their output. A SARIF converter which converts the output of such an analysis tool to the SARIF format SHALL NOT set ruleId, and in particular, it SHALL NOT attempt to synthesize it from other information available in the original analysis tool's output."_

based on your link i think we've got an answer, we should set it when we have it otherwise leave it empty

**Comment by anthturner** [comment]
Wow, go me for not even attempting to read that bit. Absolutely great catch and I appreciate it.

**Comment by iancardosozup** [comment]
i'm closing the issue since we both agree.
Thanks for the contribution, people like you that motivates us to do our best.

**Comment by anthturner** [comment]
QQ before this completely dies, I noticed Semgrep seemed to have this but it wasn't exposed. Sure, we can't generate new IDs, but if the app provides it and it's not being passed through, is that a valid contribution to fix?

e.g. https://github.com/anthturner/horusec/blob/71f2b4939ceccca0fe4b59949785cb5c5d892d77/internal/services/formatters/generic/semgrep/formatter.go#L93

**Comment by iancardosozup** [comment]
> QQ before this completely dies, I noticed Semgrep seemed to have this but it wasn't exposed. Sure, we can't generate new IDs, but if the app provides it and it's not being passed through, is that a valid contribution to fix?
> 
> e.g. https://github.com/anthturner/horusec/blob/71f2b4939ceccca0fe4b59949785cb5c5d892d77/internal/services/formatters/generic/semgrep/formatter.go#L93
> 
> (edit: of course I am assuming in the above case I remove `SEMGREP-` from the top)


Of course it's a valid contribution(it's a very good one indeed), i think i didn't express myself correctly and prematurely closed this issue, we will add this and you can make your PR without problems.

**Comment by anthturner** [comment]
See PR #967
